# Generated by Django 4.2.5 on 2023-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_location_product_time_user_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
