# Generated by Django 4.2.5 on 2023-09-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
