# Generated by Django 4.2.5 on 2023-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_status_otp_is_verified_remove_otp_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='img/'),
        ),
    ]
