# Generated by Django 4.2.5 on 2023-09-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
