# Generated by Django 4.2.5 on 2023-09-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_question_delete_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
