# Generated by Django 4.2.5 on 2023-09-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_location_location_id_remove_price_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='hour',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
